###

stages:
  - test

link checker:
  stage: test
  allow_failure: true
  image:
    name: golang:1.14-alpine
  before_script:
    - apk add git
    - export GO111MODULE=on
    - go get -u github.com/raviqqe/liche
  script:
    - liche -r ${CI_PROJECT_DIR}

build:
  image:
    name: node:12-alpine
  stage: test
  before_script:
    - npm i --cache .npm --prefer-offline --no-audit --progress=false
  script:
    - npm run build
