export default [
  {
    logo: '/img/docs/home/logo/briskid.svg',
    whiteLogo: '/img/docs/home/logo/briskid-white.svg',
    title: 'Brisk ID',
    description:
      'allows anyone with a mobile phone to create and manage a PayString.',
    userLogo: '/img/docs/home/developers/briskid.svg',
    userName: 'Leighton Scarlett,',
    userdetail: 'Founder',
    link: 'https://devpost.com/software/briskid',
  },
  {
    logo: '/img/docs/home/logo/kyc-crypto.svg',
    whiteLogo: '/img/docs/home/logo/kyc-crypto-white.svg',
    title: 'Verified PayString',
    description: 'decentralized saved identities assigned to PayString.',
    userLogo: '/img/docs/home/developers/kyc-crypto.svg',
    userName: 'Tobias Graf,',
    userdetail: 'CEO KYC.Crypto',
    link: 'https://devpost.com/software/verified-payid',
  },
  {
    logo: '/img/docs/home/logo/insta-pay.svg',
    whiteLogo: '/img/docs/home/logo/insta-pay-white.svg',
    title: 'Instapay',
    description:
      'the fastest, easiest payment app for all financial transactions.',
    userLogo: '/img/docs/home/developers/insta-pay.svg',
    userName: 'Jayshree Anandakumar,',
    userdetail: 'Founder',
    link: 'https://devpost.com/software/instapay',
  },
  {
    logo: '/img/docs/home/logo/xnd.svg',
    whiteLogo: '/img/docs/home/logo/xnd-white.svg',
    title: 'XND',
    description:
      'a wallet that can perform cross-chain transfers directly to a PayString.',
    userLogo: '/img/docs/home/developers/xnd.svg',
    userName: 'Anirudha Bose,',
    userdetail: 'Backend Developer',
    link: 'https://devpost.com/software/xnd',
  },
  {
    logo: '/img/docs/home/logo/x-payments.svg',
    whiteLogo: '/img/docs/home/logo/x-payments-white.svg',
    title: 'Xpayments.me',
    description: 'a central gateway for cryptocurrency payment information.',
    userLogo: '/img/docs/home/developers/x-payments.svg',
    userName: 'Roshan Pawar,',
    userdetail: 'Founder',
    link: 'https://devpost.com/software/xpayments-me',
  },
  {
    logo: '/img/docs/home/logo/upay.svg',
    whiteLogo: '/img/docs/home/logo/upay-white.svg',
    title: 'Upay',
    description:
      'get paid for your online services by anyone anywhere in the world.',
    userLogo: '/img/docs/home/developers/upay.svg',
    userName: 'Konstantin Shkut,',
    userdetail: 'Founder',
    link: 'https://devpost.com/software/u-pay',
  },
  {
    logo: '/img/docs/home/logo/payid-validator.svg',
    whiteLogo: '/img/docs/home/logo/payid-validator-white.svg',
    title: 'PayString Validator',
    description:
      'a tool for performing checks to validate PayString response headers.',
    userLogo: '/img/docs/home/developers/payid-validator.svg',
    userName: 'Robert Swarthout,',
    userdetail: 'Founder',
    link: 'https://devpost.com/software/payid-validator',
  },
  {
    logo: '/img/docs/home/logo/zero-games.svg',
    whiteLogo: '/img/docs/home/logo/zero-games-white.svg',
    title: '0Games',
    description: 'a peer-to-peer 0% fee video game crypto-marketplace.',
    userLogo: '/img/docs/home/developers/zero-games.svg',
    userName: 'Aymeric Bethencourt,',
    userdetail: 'Founder',
    link: 'https://devpost.com/software/0games',
  },
  {
    logo: '/img/docs/home/logo/unisend.svg',
    whiteLogo: '/img/docs/home/logo/unisend-white.svg',
    title: 'Unisend',
    description: 'app to send money internationally for free using PayString.',
    userLogo: '/img/docs/home/developers/unisend.svg',
    userName: 'Drew Patel,',
    userdetail: 'Backend Developer',
    link: 'https://devpost.com/software/temp-project-name-duso2p',
  },
]
